name: Lint  on pull requests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: "*"
# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # Need to set fetch depth to 0 for incremental diffs to grab the target branch
          fetch-depth: '0'
      - name: Run ESLint
        uses: synergy-au/eslint-action@v1
        with:
          rules-path: './.eslintrc.json'
          setup-from-package-json: 'true'
